url: "https://gradcswomen-utah.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Grad-CS Women" # the name of your site, e.g. ACME Corp.
description: "University of Utah | Kahlert School of Computing :computer:"
