# Site
name: "U of Utah Grad-CS Women"
title: "U of Utah Grad-CS Women"
description: "Promoting the representation and interests of graduate women in computer science. "
logo: '/assets/images/header_logo.png'
favicon: '/assets/images/header_logo.png'
baseurl: ""
mailchimp-list: 
include: ["_pages", "_officers"]
permalink: /:title/

# Authors
authors:
  cswomen:
    name: Grad-CS Women
    display_name: Grad-CS Women
    email: cswomenleadership@gmail.com
    avatar: '/assets/images/avatars/cswomen.png'
    twitter: https://twitter.com/cswomenumass
  Mahnoor:
    avatar: '/assets/images/officers/mahnoor.png'
    display_name: Mahnoor Fatima Saad
  Estelle:
    avatar: '/assets/images/officers/estelle.png'
    display_name: Estelle
  Manila:
    avatar: '/assets/images/officers/manila.png'
    display_name: Manila
  Milena:
    avatar: '/assets/images/officers/milena.png'
    display_name: Milena
  Mayukha:
    avatar: '/assets/images/officers/mayukha.png'
    display_name: Mayukha
  Shiyi:
    avatar: '/assets/images/officers/xyz.png'
    display_name: Shiyi
  Anna:
    avatar: '/assets/images/officers/anna.png'
    display_name: Dr. Anna Fariha
  Sakshi:
    avatar: '/assets/images/officers/sakshi.png'
    display_name: Sakshi
  LeAnn:
    avatar: '/assets/images/officers/xyz.png'
    display_name: LeAnn Lindsey
    
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 3
paginate_path: "blog/page:num"
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

collections:
  - officers
