# Site
name: "U of Utah Grad-CS Women"
title: "U of Utah Grad-CS Women"
description: "Promoting the representation and interests of graduate women in computer science. "
logo: '/assets/images/header_logo.png'
favicon: '/assets/images/header_logo.png'
baseurl: ""
mailchimp-list: 
include: ["_pages", "_officers"]
permalink: /:title/

# Authors
authors:
  cswomen:
    name: Grad-CS Women
    display_name: Grad-CS Women
    email: gradcswomen@gmail.com
    avatar: '/assets/images/avatars/cswomen.png'
    twitter: https://twitter.com/cswomenumass
  Mahnoor:
    avatar: '/assets/images/officers/mahnoor.png'
    display_name: Mahnoor Fatima Saad
  Kimberly:
    avatar: '/assets/images/officers/kimberly.png'
    display_name: Kimberly
  Rebecca:
    avatar: '/assets/images/officers/rebecca.png'
    display_name: Rebecca
  LeAnn:
    avatar: '/assets/images/officers/xyz.png'
    display_name: LeAnn Lindsey
    
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 3
paginate_path: "blog/page:num"
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

collections:
  - officers
